name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django

      - name: Run Django checks
        run: |
          python manage.py check

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Collect static files
        env:
          DJANGO_SETTINGS_MODULE: studio_site.settings
        run: |
          python manage.py collectstatic --noinput
